<script setup lang="ts">
useSeoMeta({
    title: 'Mockbukkit | Privacy Policy – Protecting Your Data',
    description: 'MockBukkit is a powerful mocking framework for unit testing Bukkit plugins. It provides a comprehensive mock implementation of CraftBukkit, allowing developers to efficiently test their plugins with ease. Explore features like mock players, worlds, and plugins, making your testing more robust and streamlined.',
    ogTitle: 'Mockbukkit | Privacy Policy – Protecting Your Data',
    ogDescription: 'MockBukkit is a powerful mocking framework for unit testing Bukkit plugins. It provides a comprehensive mock implementation of CraftBukkit, allowing developers to efficiently test their plugins with ease. Explore features like mock players, worlds, and plugins, making your testing more robust and streamlined.',
    ogSiteName: 'Mockbukkit',
    ogUrl: 'https://mockbukkit.org',
    ogType: 'website',
    ogImage: 'https://raw.githubusercontent.com/MockBukkit/MockBukkit/v1.21/logo.png',
    twitterTitle: 'Mockbukkit | Privacy Policy – Protecting Your Data',
    twitterDescription: 'MockBukkit is a powerful mocking framework for unit testing Bukkit plugins. It provides a comprehensive mock implementation of CraftBukkit, allowing developers to efficiently test their plugins with ease. Explore features like mock players, worlds, and plugins, making your testing more robust and streamlined.',
    twitterImage: 'https://raw.githubusercontent.com/MockBukkit/MockBukkit/v1.21/logo.png',
    twitterCard: 'summary',
})
</script>

<template>
    <div class="container max-w-screen-lg text-white mx-auto text-justify">
        <div class="my-8">
            <h1 class="font-bold text-center text-2xl" id="privacy-policy">Privacy Policy</h1>
            <p class="text-neutral-500 text-center"><strong>Effective Date:</strong> August 3, 2024</p>
        </div>
        <p>Thank you for visiting <a class="hover:underline text-green-500" href="https://mockbukkit.org">https://mockbukkit.org</a>. We value your privacy and want to be transparent about the data we
            collect, how we use it, and your rights regarding your personal information. This Privacy Policy outlines our practices.</p>

        <h2 id="1-general-information">1. General Information</h2>
        <p>MockBukkit is an open-source project, and we are committed to protecting your privacy. If you have any questions or concerns about our privacy practices,
            please contact us at <a class="hover:underline text-green-500"  href="mailto:privacy@mockbukkit.org.">privacy@mockbukkit.org.</a></p>
        <h2 id="2-definitions">2. Definitions</h2>
        <ul>
            <li><strong>Personal Data</strong>: Any information relating to an identified or identifiable individual.</li>
            <li><strong>Usage Data</strong>: Data collected automatically, either generated by the use of the website or from the website infrastructure itself.
            </li>
        </ul>
        <h2 id="3-data-collection">3. Data Collection</h2>
        <p>We do not collect any personal information such as names or email addresses. However, we do collect certain usage data to improve our website.</p>
        <h2 id="4-usage-data">4. Usage Data</h2>
        <p>We collect the following information when you visit our website:</p>
        <ul>
            <li>IP address</li>
            <li>Browser type</li>
            <li>Time spent on our website</li>
        </ul>
        <h2 id="5-cookies-and-tracking-technologies">5. Cookies and Tracking Technologies</h2>
        <p>We use cookies and similar tracking technologies to provide essential and performance-related functionalities:</p>
        <ul>
            <li><strong>Essential Cookies</strong>: Necessary for the website to function properly.</li>
            <li><strong>Performance Cookies</strong>: Help us understand how visitors interact with our website by collecting and reporting information anonymously.
            </li>
        </ul>
        <h2 id="6-third-party-services">6. Third-Party Services</h2>
        <p>We do not use any third-party services that collect information on our behalf.</p>
        <h2 id="7-purpose-of-data-collection">7. Purpose of Data Collection</h2>
        <p>We use the collected data to improve our website and enhance your browsing experience.</p>
        <h2 id="8-data-sharing">8. Data Sharing</h2>
        <p>We do not share user data with any third parties.</p>
        <h2 id="9-data-retention">9. Data Retention</h2>
        <p>We retain the collected data for one year.</p>
        <h2 id="10-user-rights">10. User Rights</h2>
        <p>You have the right to access, update, or delete your information. To exercise these rights, please contact us at privacy@mockbukkit.org.</p>
        <h2 id="11-opt-out">11. Opt-Out</h2>
        <p>If you wish to opt-out of data collection or marketing communications, please contact us at privacy@mockbukkit.org.</p>
        <h2 id="12-data-protection-measures">12. Data Protection Measures</h2>
        <p>We are committed to ensuring the security of your information. We have implemented the following measures to protect your data against unauthorized
            access, alteration, disclosure, or destruction:</p>
        <ul>
            <li><strong>SSL/TLS Encryption</strong>: We use SSL/TLS encryption to secure data transmission between your browser and our servers.</li>
            <li><strong>Firewalls and Intrusion Detection Systems</strong>: We employ firewalls and intrusion detection systems to monitor and protect our network
                from unauthorized access.
            </li>
            <li><strong>Software Updates and Patches</strong>: We regularly update and patch our software to address security vulnerabilities.</li>
            <li><strong>Access Controls</strong>: Access to data is restricted to authorized personnel only.</li>
            <li><strong>Security Audits and Assessments</strong>: We conduct regular security audits and assessments to identify and mitigate potential risks.</li>
        </ul>
        <h2 id="13-data-storage-locations">13. Data Storage Locations</h2>
        <p>We use Cloudflare services for our website, and data may be processed and stored on servers located in various regions. Cloudflare adheres to strict data
            protection and privacy standards.</p>
        <h2 id="14-third-party-links">14. Third-Party Links</h2>
        <p>Our website may contain links to third-party websites. We are not responsible for the privacy practices or the content of these websites. We encourage
            you to review the privacy policies of any third-party sites you visit.</p>
        <h2 id="15-dispute-resolution">15. Dispute Resolution</h2>
        <p>If you have any concerns or disputes regarding our privacy practices, please contact us at privacy@mockbukkit.org. We will work with you to resolve any
            issues promptly.</p>
        <h2 id="16-consent">16. Consent</h2>
        <p>By using our website, you consent to our collection and use of your data as described in this Privacy Policy.</p>
        <h2 id="17-legal-requirements">17. Legal Requirements</h2>
        <p>We comply with the General Data Protection Regulation (GDPR), the California Consumer Privacy Act (CCPA), the Personal Information Protection and
            Electronic Documents Act (PIPEDA), the Australian Privacy Act 1988, and the Protection of Personal Information Act (POPIA) of South Africa.</p>
        <h2 id="18-gdpr-european-union">18. GDPR (European Union)</h2>
        <p>If you are a resident of the European Union, you have the following rights under the GDPR:</p>
        <ul>
            <li><strong>Right to Access</strong>: You have the right to request access to your personal data.</li>
            <li><strong>Right to Rectification</strong>: You have the right to request the correction of inaccurate personal data.</li>
            <li><strong>Right to Erasure</strong>: You have the right to request the deletion of your personal data.</li>
            <li><strong>Right to Restrict Processing</strong>: You have the right to request the restriction of processing your personal data.</li>
            <li><strong>Right to Data Portability</strong>: You have the right to request the transfer of your personal data to another organization.</li>
            <li><strong>Right to Object</strong>: You have the right to object to the processing of your personal data.</li>
            <li><strong>Right to Withdraw Consent</strong>: You have the right to withdraw your consent at any time.</li>
        </ul>
        <h2 id="19-ccpa-california-usa">19. CCPA (California, USA)</h2>
        <p>If you are a resident of California, you have the following rights under the CCPA:</p>
        <ul>
            <li><strong>Right to Know</strong>: You have the right to know what personal data is being collected about you.</li>
            <li><strong>Right to Delete</strong>: You have the right to request the deletion of your personal data.</li>
            <li><strong>Right to Opt-Out</strong>: You have the right to opt-out of the sale of your personal data.</li>
            <li><strong>Right to Non-Discrimination</strong>: You have the right to not be discriminated against for exercising your privacy rights.</li>
        </ul>
        <h2 id="20-pipeda-canada">20. PIPEDA (Canada)</h2>
        <p>If you are a resident of Canada, you have the following rights under PIPEDA:</p>
        <ul>
            <li><strong>Right to Access</strong>: You have the right to request access to your personal data.</li>
            <li><strong>Right to Challenge</strong>: You have the right to challenge the accuracy and completeness of your personal data and have it amended as
                appropriate.
            </li>
            <li><strong>Right to Withdraw Consent</strong>: You have the right to withdraw your consent at any time, subject to legal or contractual restrictions.
            </li>
        </ul>
        <h2 id="21-australian-privacy-act-1988-australia">21. Australian Privacy Act 1988 (Australia)</h2>
        <p>If you are a resident of Australia, you have the following rights under the Australian Privacy Act 1988:</p>
        <ul>
            <li><strong>Right to Access</strong>: You have the right to request access to your personal data.</li>
            <li><strong>Right to Correct</strong>: You have the right to request the correction of inaccurate personal data.</li>
        </ul>
        <h2 id="22-popia-south-africa">22. POPIA (South Africa)</h2>
        <p>If you are a resident of South Africa, you have the following rights under the Protection of Personal Information Act (POPIA):</p>
        <ul>
            <li><strong>Right to Access</strong>: You have the right to request access to your personal data.</li>
            <li><strong>Right to Correction or Deletion</strong>: You have the right to request the correction or deletion of your personal data.</li>
            <li><strong>Right to Object</strong>: You have the right to object to the processing of your personal data.</li>
            <li><strong>Right to Withdraw Consent</strong>: You have the right to withdraw your consent at any time.</li>
            <li><strong>Right to Complain</strong>: You have the right to lodge a complaint with the Information Regulator if you believe your rights under POPIA
                have been infringed.
            </li>
        </ul>
        <h2 id="23-childrens-privacy">23. Children&#39;s Privacy</h2>
        <p>We do not knowingly collect information from children under the age of 13.</p>
        <h2 id="24-policy-updates">24. Policy Updates</h2>
        <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page. Please review it periodically for updates.</p>
        <h2 id="25-contact-information">25. Contact Information</h2>
        <p>If you have any questions or concerns about this Privacy Policy or our data practices, please contact us at <a href="mailto:privacy@mockbukkit.org">privacy@mockbukkit.org</a>.</p>

    </div>
</template>

<style lang="postcss" scoped>
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
    h2 {
        @apply text-2xl mt-6 mb-3 font-bold
    }

    a {
        @apply hover:underline text-green-500
    }

    ul {
        @apply list-disc ml-8
    }
}
</style>
